### ISSUE TITLE
Compile error on sample code

### ISSUE THREAD

**Issue by HectorIX** [stephank/tokio-smtp#2]
Hello, I need to send an email using tokio-core and tokio-smtp. 

I found this example at: `https://docs.rs/tokio-smtp/0.2.0/tokio_smtp/`

`extern crate tokio_core;
extern crate tokio_smtp;

use tokio_core::reactor::{Core};
use tokio_smtp::{Mailer};

fn main() {
    // Create the event loop that will drive this server.
    let mut core = Core::new().unwrap();
    let handle = core.handle();

    // Create a mailer that delivers to `localhost:25`.
    let mailer = Mailer::local();

    // Send an email. The `send` method returns an empty future (`()`).
    let return_path = "john@example.test".parse().unwrap();
    let recipient = "alice@example.test".parse().unwrap();
    let body = "hello world\n".to_string();
    let f = mailer.send(return_path, vec![recipient], body, &handle);

    // Start the client on the event loop.
    core.run(f).unwrap();
}`

and when I **cargo run** it, I get: (on Linux-Mint 18.1)

`error[E0308]: mismatched types
   --> /home/hector/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-smtp-0.2.0/src/response.rs:293:31
    |
293 |                         char!(b'-'),
    |                               ^^^^ expected char, found u8

error[E0308]: mismatched types
   --> /home/hector/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-smtp-0.2.0/src/response.rs:304:35
    |
304 |                             char!(b' '),
    |                                   ^^^^ expected char, found u8

error: aborting due to previous error(s)

error: Could not compile `tokio-smtp`.
`

Is this a bug? Can you give a working example? I just need to send to myaccount@gmail.com an email with a body and a subject.

**Comment by stephank** [comment]
This was fixed by @katyo!

I guess it was a bug. Weird one, though! Like `nom` broke something in the 2.x release line.
